### ISSUE TITLE
New release on PyPI

### ISSUE THREAD

**Issue by WoLpH** [disqus/django-bitfield#88]
The current release is over 2 years old and obviously not in sync with the master branch. From what I can gather, the master branch should work with Django 2.x whereas the current PyPI release does not (fully).

The widgets lack the `renderer` parameter it seems

**Comment by timabbott** [comment]
@WoLpH this is my fault, in that I a couple months ago got permission to do uploads, but haven't actually done so yet.  I'll try to make it happen soon.

**Comment by WoLpH** [comment]
awesome! that would be great.

I've tested the extension in django 2.1 and so far haven't seen any issues

**Comment by dalvtor** [comment]
Thanks for this!

**Comment by rhysyngsun** [comment]
Any progress on this? I had to workaround by excluding `BitField`s from django-admin, which is not ideal.

**Comment by timabbott** [comment]
Not before today.  I've been suffering from a chronic illness that really limits my free time.

But I've just gone ahead and did an upload; actually 2, because this package wasn't compliant with the new pypi standards for how to store descriptions.

So fixed in 1.9.5.  Thanks for the prodding.

If there are other issues in this project you'd like to see fixed, submit PRs with tests.  It shouldn't be hard to do future releases now that I've done one.
